chore: avoid errors stemming from unused-parameter
Hey, we talked briefly on wroc_love.rb today :)

I still don't understand why it's happening on my nixOS setup but doesn't
trigger in CI nor on your machine.
But to the best of my understanding this should happen always on current main?

Relevant log below:
```
/nix/store/3zcs23yc1wbjkmd7s1fp7dncvy17dhr3-gnumake-4.4.1/bin/make
compiling ../../../../ext/um/um.c
In file included from /nix/store/j7w4vyc3m1icw293l43lnj1dczdz5i0n-ruby-4.0.2/include/ruby-4.0.0/ruby/internal/core/rarray.h:32,
                 from /nix/store/j7w4vyc3m1icw293l43lnj1dczdz5i0n-ruby-4.0.2/include/ruby-4.0.0/ruby/internal/core.h:23,
                 from /nix/store/j7w4vyc3m1icw293l43lnj1dczdz5i0n-ruby-4.0.2/include/ruby-4.0.0/ruby/ruby.h:29,
                 from /nix/store/j7w4vyc3m1icw293l43lnj1dczdz5i0n-ruby-4.0.2/include/ruby-4.0.0/ruby.h:38,
                 from ../../../../ext/um/um.h:4,
                 from ../../../../ext/um/um.c:1:
/nix/store/j7w4vyc3m1icw293l43lnj1dczdz5i0n-ruby-4.0.2/include/ruby-4.0.0/ruby/internal/gc.h: In function ‘rb_gc_force_recycle’:
/nix/store/j7w4vyc3m1icw293l43lnj1dczdz5i0n-ruby-4.0.2/include/ruby-4.0.0/ruby/internal/gc.h:827:46: error: unused parameter ‘obj’ [-Werror=unused-parameter]
  827 | static inline void rb_gc_force_recycle(VALUE obj){}
      |                                        ~~~~~~^~~
../../../../ext/um/um.c: In function ‘um_profile_wait_cqe_pre’:
../../../../ext/um/um.c:285:48: error: unused parameter ‘machine’ [-Werror=unused-parameter]
  285 | inline void um_profile_wait_cqe_pre(struct um *machine, double *time_monotonic0, VALUE *fiber) {
      |                                     ~~~~~~~~~~~^~~~~~~
../../../../ext/um/um.c:285:89: error: unused parameter ‘fiber’ [-Werror=unused-parameter]
  285 | inline void um_profile_wait_cqe_pre(struct um *machine, double *time_monotonic0, VALUE *fiber) {
      |                                                                                  ~~~~~~~^~~~~
../../../../ext/um/um.c: In function ‘um_profile_wait_cqe_post’:
../../../../ext/um/um.c:294:88: error: unused parameter ‘fiber’ [-Werror=unused-parameter]
  294 | inline void um_profile_wait_cqe_post(struct um *machine, double time_monotonic0, VALUE fiber) {
      |                                                                                  ~~~~~~^~~~~
../../../../ext/um/um.c: In function ‘um_profile_switch’:
../../../../ext/um/um.c:360:42: error: unused parameter ‘machine’ [-Werror=unused-parameter]
  360 | inline void um_profile_switch(struct um *machine, VALUE next_fiber) {
      |                               ~~~~~~~~~~~^~~~~~~
../../../../ext/um/um.c:360:57: error: unused parameter ‘next_fiber’ [-Werror=unused-parameter]
  360 | inline void um_profile_switch(struct um *machine, VALUE next_fiber) {
      |                                                   ~~~~~~^~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [Makefile:251: um.o] Error 1
```